AWSTemplateFormatVersion: '2010-09-09'
Description: AWS accounts via Control Tower Account Factory

Parameters:
  AccountFactoryProductId:
    Type: String
    Description: Product ID for AWS Control Tower Account Factory
  AccountFactoryArtifactId:
    Type: String
    Description: Active Provisioning Artifact ID for Account Factory
  ProjectPrefixLower:
    Type: String
    Default: acme
    Description: Lowercase project prefix used for CloudFormation exports

  # Network account
  NetworkAccountEmail:
    Type: String
  NetworkUserEmail:
    Type: String
  NetworkUserFirstName:
    Type: String
  NetworkUserLastName:
    Type: String

  # Shared Services account
  SharedServicesAccountEmail:
    Type: String
  SharedServicesUserEmail:
    Type: String
  SharedServicesUserFirstName:
    Type: String
  SharedServicesUserLastName:
    Type: String

  # Dev account
  DevAccountEmail:
    Type: String
  DevUserEmail:
    Type: String
  DevUserFirstName:
    Type: String
  DevUserLastName:
    Type: String

  # ==============================================================================
  # Uncomment the following parameters when the Test account is required.
  # ==============================================================================
  # TestAccountEmail:
  #   Type: String
  # TestUserEmail:
  #   Type: String
  # TestUserFirstName:
  #   Type: String
  # TestUserLastName:
  #   Type: String

  # ==============================================================================
  # Uncomment the following parameters when the Stage account is required.
  # ==============================================================================
  # StageAccountEmail:
  #   Type: String
  # StageUserEmail:
  #   Type: String
  # StageUserFirstName:
  #   Type: String
  # StageUserLastName:
  #   Type: String

  # Prod account
  ProdAccountEmail:
    Type: String
  ProdUserEmail:
    Type: String
  ProdUserFirstName:
    Type: String
  ProdUserLastName:
    Type: String

  # ==============================================================================
  # Uncomment the following parameters when the Sandbox account is required.
  # ==============================================================================
  # SandboxAccountEmail:
  #   Type: String
  # SandboxUserEmail:
  #   Type: String
  # SandboxUserFirstName:
  #   Type: String
  # SandboxUserLastName:
  #   Type: String

Resources:
  # ==============================================================================
  # INFRASTRUCTURE ACCOUNTS
  # ==============================================================================
  NetworkAccount:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductId: !Ref AccountFactoryProductId
      ProvisioningArtifactId: !Ref AccountFactoryArtifactId
      ProvisionedProductName: Network
      ProvisioningParameters:
        - Key: AccountName
          Value: Network
        - Key: AccountEmail
          Value: !Ref NetworkAccountEmail
        - Key: ManagedOrganizationalUnit
          Value: Infrastructure
        - Key: SSOUserEmail
          Value: !Ref NetworkUserEmail
        - Key: SSOUserFirstName
          Value: !Ref NetworkUserFirstName
        - Key: SSOUserLastName
          Value: !Ref NetworkUserLastName

  SharedServicesAccount:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    DependsOn: NetworkAccount
    Properties:
      ProductId: !Ref AccountFactoryProductId
      ProvisioningArtifactId: !Ref AccountFactoryArtifactId
      ProvisionedProductName: SharedServices
      ProvisioningParameters:
        - Key: AccountName
          Value: Shared Services
        - Key: AccountEmail
          Value: !Ref SharedServicesAccountEmail
        - Key: ManagedOrganizationalUnit
          Value: Infrastructure
        - Key: SSOUserEmail
          Value: !Ref SharedServicesUserEmail
        - Key: SSOUserFirstName
          Value: !Ref SharedServicesUserFirstName
        - Key: SSOUserLastName
          Value: !Ref SharedServicesUserLastName

  # ==============================================================================
  # WORKLOAD ACCOUNTS
  # ==============================================================================
  DevAccount:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    DependsOn: SharedServicesAccount
    Properties:
      ProductId: !Ref AccountFactoryProductId
      ProvisioningArtifactId: !Ref AccountFactoryArtifactId
      ProvisionedProductName: Dev
      ProvisioningParameters:
        - Key: AccountName
          Value: Dev
        - Key: AccountEmail
          Value: !Ref DevAccountEmail
        - Key: ManagedOrganizationalUnit
          Value: Workloads
        - Key: SSOUserEmail
          Value: !Ref DevUserEmail
        - Key: SSOUserFirstName
          Value: !Ref DevUserFirstName
        - Key: SSOUserLastName
          Value: !Ref DevUserLastName

  # ==============================================================================
  # Uncomment the following resource when the Test account is required.
  # Remember to update the DependsOn of the next account in the chain.
  # ==============================================================================
  # TestAccount:
  #   Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
  #   DependsOn: DevAccount
  #   Properties:
  #     ProductId: !Ref AccountFactoryProductId
  #     ProvisioningArtifactId: !Ref AccountFactoryArtifactId
  #     ProvisionedProductName: Test
  #     ProvisioningParameters:
  #       - Key: AccountName
  #         Value: Test
  #       - Key: AccountEmail
  #         Value: !Ref TestAccountEmail
  #       - Key: ManagedOrganizationalUnit
  #         Value: Workloads
  #       - Key: SSOUserEmail
  #         Value: !Ref TestUserEmail
  #       - Key: SSOUserFirstName
  #         Value: !Ref TestUserFirstName
  #       - Key: SSOUserLastName
  #         Value: !Ref TestUserLastName

  # ==============================================================================
  # Uncomment the following resource when the Stage account is required.
  # Remember to update the DependsOn of the next account in the chain.
  # ==============================================================================
  # StageAccount:
  #   Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
  #   DependsOn: TestAccount
  #   Properties:
  #     ProductId: !Ref AccountFactoryProductId
  #     ProvisioningArtifactId: !Ref AccountFactoryArtifactId
  #     ProvisionedProductName: Stage
  #     ProvisioningParameters:
  #       - Key: AccountName
  #         Value: Stage
  #       - Key: AccountEmail
  #         Value: !Ref StageAccountEmail
  #       - Key: ManagedOrganizationalUnit
  #         Value: Workloads
  #       - Key: SSOUserEmail
  #         Value: !Ref StageUserEmail
  #       - Key: SSOUserFirstName
  #         Value: !Ref StageUserFirstName
  #       - Key: SSOUserLastName
  #         Value: !Ref StageUserLastName

  ProdAccount:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    DependsOn: DevAccount
    Properties:
      ProductId: !Ref AccountFactoryProductId
      ProvisioningArtifactId: !Ref AccountFactoryArtifactId
      ProvisionedProductName: Prod
      ProvisioningParameters:
        - Key: AccountName
          Value: Prod
        - Key: AccountEmail
          Value: !Ref ProdAccountEmail
        - Key: ManagedOrganizationalUnit
          Value: Workloads
        - Key: SSOUserEmail
          Value: !Ref ProdUserEmail
        - Key: SSOUserFirstName
          Value: !Ref ProdUserFirstName
        - Key: SSOUserLastName
          Value: !Ref ProdUserLastName

  # ==============================================================================
  # Uncomment the following resource when the Sandbox account is required.
  # Remember to also uncomment the Sandbox OU in 2-ous.yaml.
  # ==============================================================================
  # SandboxAccount:
  #   Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
  #   DependsOn: ProdAccount
  #   Properties:
  #     ProductId: !Ref AccountFactoryProductId
  #     ProvisioningArtifactId: !Ref AccountFactoryArtifactId
  #     ProvisionedProductName: Sandbox
  #     ProvisioningParameters:
  #       - Key: AccountName
  #         Value: Sandbox
  #       - Key: AccountEmail
  #         Value: !Ref SandboxAccountEmail
  #       - Key: ManagedOrganizationalUnit
  #         Value: Sandbox
  #       - Key: SSOUserEmail
  #         Value: !Ref SandboxUserEmail
  #       - Key: SSOUserFirstName
  #         Value: !Ref SandboxUserFirstName
  #       - Key: SSOUserLastName
  #         Value: !Ref SandboxUserLastName

Outputs:
  NetworkAccountId:
    Description: AWS Account ID for the Network account
    Value: !GetAtt NetworkAccount.Outputs.AccountId
    Export:
      Name: !Sub '${ProjectPrefixLower}-accounts-NetworkAccountId'

  SharedServicesAccountId:
    Description: AWS Account ID for the Shared Services account
    Value: !GetAtt SharedServicesAccount.Outputs.AccountId
    Export:
      Name: !Sub '${ProjectPrefixLower}-accounts-SharedServicesAccountId'

  DevAccountId:
    Description: AWS Account ID for the Dev account
    Value: !GetAtt DevAccount.Outputs.AccountId
    Export:
      Name: !Sub '${ProjectPrefixLower}-accounts-DevAccountId'

  ProdAccountId:
    Description: AWS Account ID for the Prod account
    Value: !GetAtt ProdAccount.Outputs.AccountId
    Export:
      Name: !Sub '${ProjectPrefixLower}-accounts-ProdAccountId'
